server:
  host: localhost
  port: 8080
database:
  host: localhost
  port: 3306
channel:
  - type: qqbot
      url: http://localhost:5700/
      groupId: 1
  - type: wechat
      url: http://localhost:5701/
      groupId: 2